### ISSUE TITLE
Adding and immediately removing a partial does not remove the stamped HTML

### ISSUE THREAD

**Issue by andwah** [StarcounterPrefabs/launcher-include#15]
Caught in Warehouse solution, found by @miyconst.

**Comment by miyconst** [comment]
The issue was caught in the following scenario:

1. Click a button.
2. Server handles the button click.
3. Server responses with a patch which contains a new partial and schedules a task on the session.
4. The task removes the partial and sends a new patch to the client.
5. **The partial object removed from the view-model, but stamped HTML still stays on the page.**

If I add a `setTimeout` in the `partialChanged` handler, then everything works as expected, same thing if I add `Thread.Sleep` on the step 4.

**Comment by miyconst** [comment]
cc @tomalec, @warpech

**Comment by tomalec** [comment]
For what we have tested today with @andwah the issue no longer appears.
It wa either already fixed, or the race conditions may pop up later.

Anders will check during his further development whether it happens in other cases, or is totally gone.

**Comment by andwah** [comment]
I have not experienced this for a while now so im closing this issue.
